# Generated by Django 6.0.6 on 2026-06-10 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='entrada')),
                ('check_out', models.DateField(verbose_name='saída')),
                ('guests', models.PositiveIntegerField(verbose_name='hóspedes')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preço total')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Recusada'), ('CANCELLED', 'Cancelada')], db_index=True, default='PENDING', max_length=10)),
                ('card_holder', models.CharField(max_length=100, verbose_name='titular do cartão')),
                ('card_last4', models.CharField(max_length=4, verbose_name='últimos 4 dígitos')),
                ('card_brand', models.CharField(blank=True, max_length=20, verbose_name='bandeira')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='hóspede')),
            ],
            options={
                'verbose_name': 'reserva',
                'ordering': ['-created_at'],
            },
        ),
    ]
